import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ProvidersSession } from "@/providers/ProvidersSession";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Collage Frontend",
  description: "Generated by Automatic Collage",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProvidersSession>{children}</ProvidersSession>
      </body>
    </html>
  );
}
